### ISSUE TITLE
dockerデプロイ環境見直し

### ISSUE THREAD

**Issue by s-hirano-ist** [s-hirano-ist/s-private#249]
pnpm startではなくて、nodeコマンドを使う等

**Comment by camrionnvmff** [comment]
nodeコマンドを使用すると、依存階層を減らすことができ、起動速度を上げることができます。

まず、Dockerfileファイルにnodeコマンドを使用してアプリケーションを起動するように正しく設定されていることを確認します。次はDockerfileの例です。プロジェクトがノード.jsアプリケーションであると仮定します。

#ベースミラーとして公式のNode.jsミラーを使用
FROM node:14

#作業ディレクトリの設定
WORKDIR /app

#package.jsonとpnpm-lock.yamlファイルをコピー
COPY package.json pnpm-lock.yaml ./

#pnpmをインストールする
RUN npm install -g pnpm

#プロジェクト依存のインストール
RUN pnpm install

#プロジェクトファイルのコピー
COPY . .

#アプリケーションが実行しているポートの露出
EXPOSE 3000

#nodeコマンドを使用したアプリケーションの起動
CMD ["node", "index.js"]
この例では、pnpm startではなくnodeコマンドを使用してアプリケーションを開始します。index.jsファイルがアプリケーションのエントリファイルであることを確認する必要があります。ポータルファイルの名前が異なる場合は、CMDコマンドを適切に変更してください。

次に、次のコマンドを使用してDockerミラーを構築して実行できます。

#Dockerミラーの構築
docker build -t your-app-name .

#Dockerコンテナの実行
docker run -p 3000:3000 your-app-name
このようにして、あなたのアプリケーションはpnpm startではなくnodeコマンドを使用して起動します。

実際にMACを使っているなら、Serverbayを使うことをお勧めします。このツールはmacにnode.jsとPhpを合わせるのに適しています。
